### ISSUE TITLE
planning_python missing

### ISSUE THREAD

**Issue by AliJavadiGithub** [mohakbhardwaj/SaIL#1]
Hi
There is no planning_python module in the repository
Did you forget to push it?
Thanks

**Comment by madratman** [comment]
Did you read the readme?
Step 3 says `Get the search based planning backend: git clone git@github.com:mohakbhardwaj/planning_python.git`

**Comment by AliJavadiGithub** [comment]
Yes. But readme is updated after I asked this question.
